[package]
name = "hello-wasi"
version = "0.1.0"
description = ""

[[module]]
name = "hello-wasi"
source = "target/wasm32-wasi/release/hello-wasi.wasm"

[[command]]
name = "hello-wasi"
module = "hello-wasi"

